### ISSUE TITLE
`image: consul` no longer works.

### ISSUE THREAD

**Issue by McGoffmann** [g0t4/course2-consul-gs#1]
`image: consul` should be updated to `image: hashicorp/consul`.
https://github.com/g0t4/course2-consul-gs/blob/f6af49c34fcafc21a55f69615f136cf733bb55f0/discover/files/compose.yml#L5

Official Image Deprecation Notice
Upcoming in Consul 1.16, we will stop publishing official Dockerhub images and publish only our Verified Publisher images. Users of Docker images should pull from "hashicorp/consul" instead of "consul". Verified Publisher images can be found at https://hub.docker.com/r/hashicorp/consul.

**Comment by g0t4** [comment]
Thanks for catching this! I will get the repo updated ASAP. I started a branch to test switching the image, after that is confirmed to work I'll merge to master.

**Comment by g0t4** [comment]
All demo envs updated to use `hashicorp/consul:1.12.0` as that was the highest version used in course. Change this tag to use a newer version. Most (if not all) will be fine with latest version but I'd rather tag the version used. Especially given previously I was using `consul:latest` implicitly and that tag was removed from the official image, thus causing the demo envs to fail!

Thanks again @McGoffmann for flagging this!

**Comment by g0t4** [comment]
Fixed in master, had to take a second stab at it b/c my local repo was outdated.

Let me know if you have any issues.
